/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO., LTD
 * SPDX-License-Identifier: LicenseRef-Espressif-Modified-MIT
 *
 * See LICENSE file for details.
 */

#pragma once

/**
 * Central device/peripheral name table for the interactive test app.
 *
 * Every name the test cases initialize or look up is resolved through a
 * BMGR_TEST_NAME_* macro. Each macro resolves to the value configured in
 * menuconfig (CONFIG_BMGR_TEST_NAME_*) when present, otherwise it falls back to
 * the reserved default name from esp_board_manager_defs.h (or the conventional
 * literal for names that have no reserved macro).
 *
 * This lets a board whose YAML uses a non-default device name (for example a
 * display device named "my_lcd" instead of "display_lcd") be tested by simply
 * overriding the name in menuconfig: both the auto-initialization (case
 * "requires") and the in-test handle/config lookups then target the actual
 * name.
 */

#include "sdkconfig.h"
#include "esp_board_manager_defs.h"

#ifdef __cplusplus
extern "C" {
#endif  /* __cplusplus */

/* Helper: prefer the menuconfig override, otherwise the provided default. */

/* ---- Devices ---- */
#ifdef CONFIG_BMGR_TEST_NAME_DISPLAY_LCD
#define BMGR_TEST_NAME_DISPLAY_LCD  CONFIG_BMGR_TEST_NAME_DISPLAY_LCD
#else
#define BMGR_TEST_NAME_DISPLAY_LCD  ESP_BOARD_DEVICE_NAME_DISPLAY_LCD
#endif  /* CONFIG_BMGR_TEST_NAME_DISPLAY_LCD */

#ifdef CONFIG_BMGR_TEST_NAME_LCD_TOUCH
#define BMGR_TEST_NAME_LCD_TOUCH  CONFIG_BMGR_TEST_NAME_LCD_TOUCH
#else
#define BMGR_TEST_NAME_LCD_TOUCH  ESP_BOARD_DEVICE_NAME_LCD_TOUCH
#endif  /* CONFIG_BMGR_TEST_NAME_LCD_TOUCH */

#ifdef CONFIG_BMGR_TEST_NAME_LCD_BRIGHTNESS
#define BMGR_TEST_NAME_LCD_BRIGHTNESS  CONFIG_BMGR_TEST_NAME_LCD_BRIGHTNESS
#else
#define BMGR_TEST_NAME_LCD_BRIGHTNESS  ESP_BOARD_DEVICE_NAME_LCD_BRIGHTNESS
#endif  /* CONFIG_BMGR_TEST_NAME_LCD_BRIGHTNESS */

#ifdef CONFIG_BMGR_TEST_NAME_LCD_POWER
#define BMGR_TEST_NAME_LCD_POWER  CONFIG_BMGR_TEST_NAME_LCD_POWER
#else
#define BMGR_TEST_NAME_LCD_POWER  ESP_BOARD_DEVICE_NAME_LCD_POWER
#endif  /* CONFIG_BMGR_TEST_NAME_LCD_POWER */

#ifdef CONFIG_BMGR_TEST_NAME_GPIO_EXPANDER
#define BMGR_TEST_NAME_GPIO_EXPANDER  CONFIG_BMGR_TEST_NAME_GPIO_EXPANDER
#else
#define BMGR_TEST_NAME_GPIO_EXPANDER  ESP_BOARD_DEVICE_NAME_GPIO_EXPANDER
#endif  /* CONFIG_BMGR_TEST_NAME_GPIO_EXPANDER */

#ifdef CONFIG_BMGR_TEST_NAME_CAMERA
#define BMGR_TEST_NAME_CAMERA  CONFIG_BMGR_TEST_NAME_CAMERA
#else
#define BMGR_TEST_NAME_CAMERA  ESP_BOARD_DEVICE_NAME_CAMERA
#endif  /* CONFIG_BMGR_TEST_NAME_CAMERA */

#ifdef CONFIG_BMGR_TEST_NAME_LED_STRIP
#define BMGR_TEST_NAME_LED_STRIP  CONFIG_BMGR_TEST_NAME_LED_STRIP
#else
#define BMGR_TEST_NAME_LED_STRIP  ESP_BOARD_DEVICE_NAME_LED_STRIP
#endif  /* CONFIG_BMGR_TEST_NAME_LED_STRIP */

#ifdef CONFIG_BMGR_TEST_NAME_LITTLEFS
#define BMGR_TEST_NAME_LITTLEFS  CONFIG_BMGR_TEST_NAME_LITTLEFS
#else
#define BMGR_TEST_NAME_LITTLEFS  ESP_BOARD_DEVICE_NAME_LITTLEFS
#endif  /* CONFIG_BMGR_TEST_NAME_LITTLEFS */

#ifdef CONFIG_BMGR_TEST_NAME_FS_SPIFFS
#define BMGR_TEST_NAME_FS_SPIFFS  CONFIG_BMGR_TEST_NAME_FS_SPIFFS
#else
#define BMGR_TEST_NAME_FS_SPIFFS  ESP_BOARD_DEVICE_NAME_FS_SPIFFS
#endif  /* CONFIG_BMGR_TEST_NAME_FS_SPIFFS */

#ifdef CONFIG_BMGR_TEST_NAME_FS_FAT
#define BMGR_TEST_NAME_FS_FAT  CONFIG_BMGR_TEST_NAME_FS_FAT
#else
#define BMGR_TEST_NAME_FS_FAT  ESP_BOARD_DEVICE_NAME_FS_FAT
#endif  /* CONFIG_BMGR_TEST_NAME_FS_FAT */

#ifdef CONFIG_BMGR_TEST_NAME_AUDIO_DAC
#define BMGR_TEST_NAME_AUDIO_DAC  CONFIG_BMGR_TEST_NAME_AUDIO_DAC
#else
#define BMGR_TEST_NAME_AUDIO_DAC  ESP_BOARD_DEVICE_NAME_AUDIO_DAC
#endif  /* CONFIG_BMGR_TEST_NAME_AUDIO_DAC */

#ifdef CONFIG_BMGR_TEST_NAME_AUDIO_ADC
#define BMGR_TEST_NAME_AUDIO_ADC  CONFIG_BMGR_TEST_NAME_AUDIO_ADC
#else
#define BMGR_TEST_NAME_AUDIO_ADC  ESP_BOARD_DEVICE_NAME_AUDIO_ADC
#endif  /* CONFIG_BMGR_TEST_NAME_AUDIO_ADC */

/* Names without a reserved default macro: fall back to the conventional literal. */
#ifdef CONFIG_BMGR_TEST_NAME_AUDIO_POWER
#define BMGR_TEST_NAME_AUDIO_POWER  CONFIG_BMGR_TEST_NAME_AUDIO_POWER
#else
#define BMGR_TEST_NAME_AUDIO_POWER  "audio_power"
#endif  /* CONFIG_BMGR_TEST_NAME_AUDIO_POWER */

#ifdef CONFIG_BMGR_TEST_NAME_CUSTOM
#define BMGR_TEST_NAME_CUSTOM  CONFIG_BMGR_TEST_NAME_CUSTOM
#else
#define BMGR_TEST_NAME_CUSTOM  "my_custom_sensor"
#endif  /* CONFIG_BMGR_TEST_NAME_CUSTOM */

#ifdef CONFIG_BMGR_TEST_NAME_GPIO_BUTTON
#define BMGR_TEST_NAME_GPIO_BUTTON  CONFIG_BMGR_TEST_NAME_GPIO_BUTTON
#else
#define BMGR_TEST_NAME_GPIO_BUTTON  "gpio_button_0"
#endif  /* CONFIG_BMGR_TEST_NAME_GPIO_BUTTON */

#ifdef CONFIG_BMGR_TEST_NAME_CUSTOM_BUTTON
#define BMGR_TEST_NAME_CUSTOM_BUTTON  CONFIG_BMGR_TEST_NAME_CUSTOM_BUTTON
#else
#define BMGR_TEST_NAME_CUSTOM_BUTTON  "button_l"
#endif  /* CONFIG_BMGR_TEST_NAME_CUSTOM_BUTTON */

#ifdef CONFIG_BMGR_TEST_NAME_KNOB
#define BMGR_TEST_NAME_KNOB  CONFIG_BMGR_TEST_NAME_KNOB
#else
#define BMGR_TEST_NAME_KNOB  ESP_BOARD_DEVICE_NAME_KNOB
#endif  /* CONFIG_BMGR_TEST_NAME_KNOB */

/* ---- Peripherals ---- */
#ifdef CONFIG_BMGR_TEST_NAME_I2C_MASTER
#define BMGR_TEST_NAME_I2C_MASTER  CONFIG_BMGR_TEST_NAME_I2C_MASTER
#else
#define BMGR_TEST_NAME_I2C_MASTER  ESP_BOARD_PERIPH_NAME_I2C_MASTER
#endif  /* CONFIG_BMGR_TEST_NAME_I2C_MASTER */

#ifdef CONFIG_BMGR_TEST_NAME_GPIO_PA_CONTROL
#define BMGR_TEST_NAME_GPIO_PA_CONTROL  CONFIG_BMGR_TEST_NAME_GPIO_PA_CONTROL
#else
#define BMGR_TEST_NAME_GPIO_PA_CONTROL  ESP_BOARD_PERIPH_NAME_GPIO_PA_CONTROL
#endif  /* CONFIG_BMGR_TEST_NAME_GPIO_PA_CONTROL */

#ifdef CONFIG_BMGR_TEST_NAME_GPIO_MONITOR
#define BMGR_TEST_NAME_GPIO_MONITOR  CONFIG_BMGR_TEST_NAME_GPIO_MONITOR
#else
#define BMGR_TEST_NAME_GPIO_MONITOR  ESP_BOARD_PERIPH_NAME_GPIO_MONITOR
#endif  /* CONFIG_BMGR_TEST_NAME_GPIO_MONITOR */

#ifdef CONFIG_BMGR_TEST_NAME_UART
#define BMGR_TEST_NAME_UART  CONFIG_BMGR_TEST_NAME_UART
#else
#define BMGR_TEST_NAME_UART  ESP_BOARD_PERIPH_NAME_UART_1
#endif  /* CONFIG_BMGR_TEST_NAME_UART */

#ifdef CONFIG_BMGR_TEST_NAME_ADC
#define BMGR_TEST_NAME_ADC  CONFIG_BMGR_TEST_NAME_ADC
#else
#define BMGR_TEST_NAME_ADC  ESP_BOARD_PERIPH_NAME_ADC
#endif  /* CONFIG_BMGR_TEST_NAME_ADC */

#ifdef CONFIG_BMGR_TEST_NAME_RMT_TX
#define BMGR_TEST_NAME_RMT_TX  CONFIG_BMGR_TEST_NAME_RMT_TX
#else
#define BMGR_TEST_NAME_RMT_TX  ESP_BOARD_PERIPH_NAME_RMT_TX
#endif  /* CONFIG_BMGR_TEST_NAME_RMT_TX */

#ifdef CONFIG_BMGR_TEST_NAME_PCNT
#define BMGR_TEST_NAME_PCNT  CONFIG_BMGR_TEST_NAME_PCNT
#else
#define BMGR_TEST_NAME_PCNT  ESP_BOARD_PERIPH_NAME_PCNT_UNIT
#endif  /* CONFIG_BMGR_TEST_NAME_PCNT */

#ifdef CONFIG_BMGR_TEST_NAME_DAC
#define BMGR_TEST_NAME_DAC  CONFIG_BMGR_TEST_NAME_DAC
#else
#define BMGR_TEST_NAME_DAC  ESP_BOARD_PERIPH_NAME_DAC
#endif  /* CONFIG_BMGR_TEST_NAME_DAC */

#ifdef CONFIG_BMGR_TEST_NAME_SDM
#define BMGR_TEST_NAME_SDM  CONFIG_BMGR_TEST_NAME_SDM
#else
#define BMGR_TEST_NAME_SDM  ESP_BOARD_PERIPH_NAME_SDM
#endif  /* CONFIG_BMGR_TEST_NAME_SDM */

#ifdef CONFIG_BMGR_TEST_NAME_MCPWM
#define BMGR_TEST_NAME_MCPWM  CONFIG_BMGR_TEST_NAME_MCPWM
#else
#define BMGR_TEST_NAME_MCPWM  ESP_BOARD_PERIPH_NAME_MCPWM
#endif  /* CONFIG_BMGR_TEST_NAME_MCPWM */

#ifdef CONFIG_BMGR_TEST_NAME_ANACMPR
#define BMGR_TEST_NAME_ANACMPR  CONFIG_BMGR_TEST_NAME_ANACMPR
#else
#define BMGR_TEST_NAME_ANACMPR  ESP_BOARD_PERIPH_NAME_ANACMPR
#endif  /* CONFIG_BMGR_TEST_NAME_ANACMPR */

#ifdef __cplusplus
}
#endif  /* __cplusplus */
